### ISSUE TITLE
Add ROY: Royale

### ISSUE THREAD

**Issue by hmexx** [VenomProtocol/venomswap-default-token-list#10]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address:  0xfe1b516A7297eb03229A8B5AfAD80703911E81cB
Token Name (from contract):  Royale
Token Decimals (from contract): 18
Token Symbol (from contract): ROY
Uniswap V2 Pair Address of Token: 

Link to the official homepage of token: https://cryptoroyale.one
Link to CoinMarketCap or CoinGecko page of token:

**Comment by 0xViper** [comment]
Manually merged
