### ISSUE TITLE
Add HPLAY: HARMONY PLAY

### ISSUE THREAD

**Issue by velantic** [VenomProtocol/venomswap-default-token-list#16]
- [X ] I understand that token listing is not required to use the Uniswap Interface with a token.
- [X ] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x66cf8375fd083e7d103d69378e9af20f1b46dc59
Token Name (from contract): HARMONY PLAY
Token Decimals (from contract): 18
Token Symbol (from contract): HPLAY
Uniswap V2 Pair Address of Token: https://info.viper.exchange/pair/0x7a234cc13d03e9b9cc1abeeda29b0977855a1e99

Link to the official homepage of token: https://harmonyplay.one
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/harmony-play

**Comment by 0xViper** [comment]
Manually merged to the community list.
