### ISSUE TITLE
Add 1PEGG: Parrot Egg

### ISSUE THREAD

**Issue by parrotdefifarm1** [VenomProtocol/venomswap-default-token-list#18]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xC36769DFcDF05B2949F206FC34C8870707D33C89
Token Name (from contract): Parrot Egg
Token Decimals (from contract): 18
Token Symbol (from contract): 1PEGG
Uniswap V2 Pair Address of Token: 0x66bb961d88b69f04736001b598cab35c3725e3a8

Link to the official homepage of token: https://harmony.parrotdefi.com/

**Comment by 0xViper** [comment]
Can you please update this PR with an accessible token image? https://github.com/VenomProtocol/venomswap-community-token-list/pull/71 - after that's done I can merge your token to the community list.

**Comment by parrotdefifarm1** [comment]
Thanks, I just updated the PR in the community token list.
