### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by moonityone** [VenomProtocol/venomswap-default-token-list#8]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x8D4F19bec883Ba20F4f295706C53F760Cd0BC2B0
Token Name (from contract): Moonity
Token Decimals (from contract): 9
Token Symbol (from contract): MOONI
Uniswap V2 Pair Address of Token: 0x8fafb20266e8579d4e8952978a9cd0e4c65bd198 

Link to the official homepage of token: moonity.one
Link to CoinMarketCap or CoinGecko page of token: not yet available

**Comment by 0xViper** [comment]
Manually merged to community list.
