### ISSUE TITLE
Add ROY: Royale Coin

### ISSUE THREAD

**Issue by hmexx** [VenomProtocol/venomswap-default-token-list#9]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 
0x1f540F1cdD642FeB0E4AA6495e3b42877e5F64Fa
one1ra2q78xavsh7krj25ey4uw6zsal97e86jdzf4u
Token Name (from contract): Royale Coin
Token Decimals (from contract): 18
Token Symbol (from contract): ROY
Uniswap V2 Pair Address of Token: 

Link to the official homepage of token: https://cryptoroyale.one
Link to CoinMarketCap or CoinGecko page of token:

**Comment by 0xViper** [comment]
Manually merged
